# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: Master
trigger: master
jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    buildConfiguration: 'Release'

  steps:
  - script: dotnet restore
    displayName: Restore
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: Build
  - script: dotnet test Tests --logger trx --collect "Code coverage"
    displayName: Test
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'